package cn.edu.nju.jw.schema;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T16:53:07.133+08:00
 * Generated source version: 3.2.3
 *
 */
@WebServiceClient(name = "MyAuthService",
                  wsdlLocation = "http://localhost:8080/wsdl/auth.wsdl",
                  targetNamespace = "http://jw.nju.edu.cn/schema")
public class MyAuthService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://jw.nju.edu.cn/schema", "MyAuthService");
    public final static QName AuthPort = new QName("http://jw.nju.edu.cn/schema", "AuthPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/wsdl/auth.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MyAuthService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/wsdl/auth.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MyAuthService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyAuthService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyAuthService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MyAuthService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MyAuthService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MyAuthService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MyAuth
     */
    @WebEndpoint(name = "AuthPort")
    public MyAuth getAuthPort() {
        return super.getPort(AuthPort, MyAuth.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyAuth
     */
    @WebEndpoint(name = "AuthPort")
    public MyAuth getAuthPort(WebServiceFeature... features) {
        return super.getPort(AuthPort, MyAuth.class, features);
    }

}
