package cn.edu.nju.jw.schema;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T16:53:07.093+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/schema", name = "MyAuth")
@XmlSeeAlso({cn.edu.nju.schema.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MyAuth {

    @WebMethod(action = "auth/verify")
    @Action(input = "auth/verifyRequest", output = "auth/verifyResponse", fault = {@FaultAction(className = IdNotFoundException.class, value = "auth/verify/Fault/IdNotFoundException"), @FaultAction(className = PswErrorException.class, value = "auth/verify/Fault/PswErrorException")})
    @WebResult(name = "验证信息", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public 验证类型 verify(
        @WebParam(partName = "parameters", name = "认证请求", targetNamespace = "http://jw.nju.edu.cn/schema")
        账号认证类型 parameters
    ) throws IdNotFoundException, PswErrorException;
}
