
package cn.edu.nju.jw.schema;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T16:53:07.067+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "AuthFault", targetNamespace = "http://jw.nju.edu.cn/schema")
public class PswErrorException extends Exception {

    private cn.edu.nju.jw.schema.AuthFaultType authFault;

    public PswErrorException() {
        super();
    }

    public PswErrorException(String message) {
        super(message);
    }

    public PswErrorException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PswErrorException(String message, cn.edu.nju.jw.schema.AuthFaultType authFault) {
        super(message);
        this.authFault = authFault;
    }

    public PswErrorException(String message, cn.edu.nju.jw.schema.AuthFaultType authFault, java.lang.Throwable cause) {
        super(message, cause);
        this.authFault = authFault;
    }

    public cn.edu.nju.jw.schema.AuthFaultType getFaultInfo() {
        return this.authFault;
    }
}
