
package group8.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T17:03:10.015+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "fault1", targetNamespace = "http://group8.group8.service.example")
public class InputFault extends Exception {

    private group8.service.fault.InputFault fault1;

    public InputFault() {
        super();
    }

    public InputFault(String message) {
        super(message);
    }

    public InputFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InputFault(String message, group8.service.fault.InputFault fault1) {
        super(message);
        this.fault1 = fault1;
    }

    public InputFault(String message, group8.service.fault.InputFault fault1, Throwable cause) {
        super(message, cause);
        this.fault1 = fault1;
    }

    public group8.service.fault.InputFault getFaultInfo() {
        return this.fault1;
    }
}
