
package group8.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T17:03:09.950+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "fault", targetNamespace = "http://group8.group8.service.example")
public class SAXException extends Exception {

    private group8.sax.SAXException fault;

    public SAXException() {
        super();
    }

    public SAXException(String message) {
        super(message);
    }

    public SAXException(String message, Throwable cause) {
        super(message, cause);
    }

    public SAXException(String message, group8.sax.SAXException fault) {
        super(message);
        this.fault = fault;
    }

    public SAXException(String message, group8.sax.SAXException fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public group8.sax.SAXException getFaultInfo() {
        return this.fault;
    }
}
