package group8.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T17:02:39.086+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://group8.group8.service", name = "ScoreManagement")
@XmlSeeAlso({group8.service.fault.ObjectFactory.class, group8.service.model.ObjectFactory.class, ObjectFactory.class, group8.sax.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ScoreManagement {

    @WebMethod
    @WebResult(name = "queryScoreOperationReturn", targetNamespace = "http://group8.group8.service", partName = "queryScoreOperationReturn")
    public ArrayOfXsdAnyType queryScoreOperation(
        @WebParam(partName = "sidList", name = "sidList", targetNamespace = "http://group8.group8.service")
                String sidList
    ) throws SAXException, InputFault;

    @WebMethod
    @WebResult(name = "deleteScoreOperationReturn", targetNamespace = "http://group8.group8.service", partName = "deleteScoreOperationReturn")
    public group8.service.model.RequestResult deleteScoreOperation(
        @WebParam(partName = "deleteScoreList", name = "deleteScoreList", targetNamespace = "http://group8.group8.service")
        ArrayOfXsdAnyType deleteScoreList
    ) throws SAXException, InputFault;

    @WebMethod
    @WebResult(name = "modifyScoreOperationReturn", targetNamespace = "http://group8.group8.service", partName = "modifyScoreOperationReturn")
    public group8.service.model.RequestResult modifyScoreOperation(
        @WebParam(partName = "modifyScoreList", name = "modifyScoreList", targetNamespace = "http://group8.group8.service")
        ArrayOfXsdAnyType modifyScoreList
    ) throws SAXException, InputFault;

    @WebMethod
    @WebResult(name = "addScoreOperationReturn", targetNamespace = "http://group8.group8.service", partName = "addScoreOperationReturn")
    public group8.service.model.RequestResult addScoreOperation(
        @WebParam(partName = "addScoreList", name = "addScoreList", targetNamespace = "http://group8.group8.service")
        ArrayOfXsdAnyType addScoreList
    ) throws SAXException, InputFault;
}
