package group8.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T17:02:39.130+08:00
 * Generated source version: 3.2.3
 *
 */
@WebServiceClient(name = "ScoreManagementService",
                  wsdlLocation = "http://localhost:8080/wsdl/ScoreManagement.wsdl",
                  targetNamespace = "http://group8.group8.service")
public class ScoreManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://group8.group8.service", "ScoreManagementService");
    public final static QName ScoreManagement = new QName("http://group8.group8.service", "ScoreManagement");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/wsdl/ScoreManagement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ScoreManagementService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/wsdl/ScoreManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ScoreManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ScoreManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ScoreManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ScoreManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ScoreManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ScoreManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ScoreManagement
     */
    @WebEndpoint(name = "ScoreManagement")
    public ScoreManagement getScoreManagement() {
        return super.getPort(ScoreManagement, ScoreManagement.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScoreManagement
     */
    @WebEndpoint(name = "ScoreManagement")
    public ScoreManagement getScoreManagement(WebServiceFeature... features) {
        return super.getPort(ScoreManagement, ScoreManagement.class, features);
    }

}
