package group8.service;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T17:03:10.120+08:00
 * Generated source version: 3.2.3
 *
 */
@WebServiceClient(name = "StudentInfoManagementService",
                  wsdlLocation = "http://localhost:8080/wsdl/StudentInfoManagement.wsdl",
                  targetNamespace = "http://group8.group8.service.example")
public class StudentInfoManagementService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://group8.group8.service.example", "StudentInfoManagementService");
    public final static QName StudentInfoManagement = new QName("http://group8.group8.service.example", "StudentInfoManagement");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/wsdl/StudentInfoManagement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentInfoManagementService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/wsdl/StudentInfoManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentInfoManagementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentInfoManagementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentInfoManagementService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StudentInfoManagementService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentInfoManagementService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentInfoManagementService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StudentInfoManagement
     */
    @WebEndpoint(name = "StudentInfoManagement")
    public StudentInfoManagement getStudentInfoManagement() {
        return super.getPort(StudentInfoManagement, StudentInfoManagement.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StudentInfoManagement
     */
    @WebEndpoint(name = "StudentInfoManagement")
    public StudentInfoManagement getStudentInfoManagement(WebServiceFeature... features) {
        return super.getPort(StudentInfoManagement, StudentInfoManagement.class, features);
    }

}
