package group8.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-04-04T17:03:10.066+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://group8.group8.service.example", name = "StudentInfoManagement")
@XmlSeeAlso({ObjectFactory.class, group8.service.fault.ObjectFactory.class, group8.service.model.ObjectFactory.class, group8.sax.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StudentInfoManagement {

    @WebMethod
    @WebResult(name = "retrieveStudentInfoOperationReturn", targetNamespace = "http://group8.group8.service.example", partName = "retrieveStudentInfoOperationReturn")
    public group8.service.model.StudentInfo retrieveStudentInfoOperation(
            @WebParam(partName = "studentToken", name = "studentToken1", targetNamespace = "http://group8.group8.service.example")
                    String studentToken
    ) throws SAXException, InputFault;

    @WebMethod
    @WebResult(name = "modifyStudentInfoOperationReturn", targetNamespace = "http://group8.group8.service.example", partName = "modifyStudentInfoOperationReturn")
    public String modifyStudentInfoOperation(
            @WebParam(partName = "studentToken", name = "studentToken", targetNamespace = "http://group8.group8.service.example")
                    String studentToken,
            @WebParam(partName = "studentInfo", name = "studentInfo", targetNamespace = "http://group8.group8.service.example")
                    group8.service.model.StudentInfo studentInfo
    ) throws SAXException, InputFault;
}
